### PR TITLE
Add Xcode 6.3 DVTPlugInCompatibilityUUID

### LINKED ISSUE #30: support for XCode 6.3
please add this into the DVTPlugInCompatibilityUUIDs key in the info.plist

9F75337B-21B4-4ADC-B558-F9CADF7073A7

thanks for the plugin

### PR DESCRIPTION
**Pull request by iv-mexx**
This fixes #30

### CODE REVIEW

**Comment by skywinder** [comment]
+1 @kattrali  please, update

**Comment by AJMiller** [comment]
+1

**Comment by ealeksandrov** [comment]
+1

**Comment by ArtSabintsev** [comment]
I have a feeling this project is abandoned. Any takers for owning it and resubmitting to Alcatraz?

**Comment by kattrali** [comment]
Not abandoned, out on leave.

**Comment by ArtSabintsev** [comment]
Understood. Thanks for the update! Appreciate the effort put in this project :)

**Pull request merged**
